version: '3.7'
services:
  app:
    container_name: app-container
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: damian
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: users_db
    command: mongod --auth

volumes:
  mongo-data: